FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 80

# Kopiere den Inhalt des Builds für die jeweilige Plattform
COPY ./publish/ /app/
ENTRYPOINT ["dotnet", "EventHorizon.dll"]
