services:
  eventhorizon:
    image: ${DOCKER_REGISTRY-}eventhorizon
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"
    restart: always
    build:
      context: .
      dockerfile: ./EventHorizon/Dockerfile