#for dev purpose
services:
  eventhorizon:
    image: ${DOCKER_REGISTRY-}eventhorizon:linux-x64
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: always
    build:
      context: .
      dockerfile: ./EventHorizon/Dockerfile.dev
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    driver: local