services:
  eventhorizon:
    image: ghcr.io/rafmon/eventhorizon:latest
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: always
    volumes:
      - sqlite_data:/app/data
      - ./logs:/app/logs

volumes:
  sqlite_data:
    driver: local