services:
  eventhorizon:
    image: ghcr.io/rafmon/eventhorizon:linux-arm64 
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: always
    volumes:
      - sqlite_data:/app/data
      - ./logs:/app/log
    devices:
      - "/dev/i2c-1:/dev/i2c-1"   

volumes:
  sqlite_data:
    driver: local