// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHorizon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EventHorizon.src.Events.Event", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EventEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EventEndOffset")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EventStart")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EventStartOffset")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEventEndRandom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEventStartRandom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventHorizon.src.Util.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SimulateI2CDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimelineDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MemoryAddress", b =>
                {
                    b.Property<int>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("MemoryAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
