name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        platform: 
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
        include:
          - platform: linux/amd64
            runtime_identifier: linux-x64
          - platform: linux/arm/v7
            runtime_identifier: linux-arm
          - platform: linux/arm64
            runtime_identifier: linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build for each platform
      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish ./EventHorizon/EventHorizon.csproj -c Release -r ${{ matrix.runtime_identifier }} --self-contained false -o ./publish/${{ matrix.platform }}
      
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  
          password: ${{ secrets.GHCR_PAT }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker buildx build --platform ${{ matrix.platform }} -f ./EventHorizon/Dockerfile -t ghcr.io/rafmon/eventhorizon:${{ matrix.platform }} --push .

  create-and-push-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
    
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/rafmon/eventhorizon:latest \
            --amend ghcr.io/rafmon/eventhorizon:linux-amd64 \
            --amend ghcr.io/rafmon/eventhorizon:linux-arm64 \
            --amend ghcr.io/rafmon/eventhorizon:linux-arm
          docker manifest push ghcr.io/rafmon/eventhorizon:latest
