name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        platform: [linux-arm, linux-arm64, linux-amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build for each platform
      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish ./EventHorizon/EventHorizon.csproj -c Release -r ${{ matrix.platform }} --self-contained false -o ./publish/${{ matrix.platform }}
      
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub actor
          password: ${{ secrets.GHCR_PAT }}  # GitHub PAT secret 

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -f ./EventHorizon/Dockerfile -t ghcr.io/rafmon/eventhorizon:${{ matrix.platform }} .
      
      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ghcr.io/rafmon/eventhorizon:${{ matrix.platform }}

  create-and-push-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/rafmon/eventhorizon:latest \
            --amend ghcr.io/rafmon/eventhorizon:linux-amd64 \
            --amend ghcr.io/rafmon/eventhorizon:linux-arm64 \
            --amend ghcr.io/rafmon/eventhorizon:linux-arm
          docker manifest push ghcr.io/rafmon/eventhorizon:latest