name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Nutze einen Linux-Runner anstelle von Windows

    strategy:
      matrix:
        platform: [linux-arm, linux-arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build for each platform
      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish ./EventHorizon/EventHorizon.csproj -c Release -r ${{ matrix.platform }} --self-contained false -o ./publish/${{ matrix.platform }}
        
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./EventHorizon # Pointing to the EventHorizon folder
          file: ./EventHorizon/Dockerfile # Specify the Dockerfile inside the EventHorizon folder
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/rafmon/eventhorizon:latest
