name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [linux-x64, linux-arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish -c Release -r ${{ matrix.platform }} --self-contained false -o ./publish/${{ matrix.platform }}
        
      - name: Build Docker Image
        run: |
          docker build -f ./Dockerfile.rpi --build-arg PLATFORM=${{ matrix.platform }} -t ghcr.io/rafmon/eventhorizon:${{ matrix.platform }} .
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/rafmon/eventhorizon:${{ matrix.platform }}
