name: Build and Push Docker Image for Linux ARM64

on:
  push:
    branches:
      - main

jobs:
  build-and-push-linux-arm64:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build for Linux ARM64
        run: |
          dotnet publish ./EventHorizon/EventHorizon.csproj -c Release -r linux-arm64 --self-contained false -o ./publish/linux-arm64

      - name: Build Docker Image
        run: |
          docker build -f ./EventHorizon/Dockerfile -t ghcr.io/rafmon/eventhorizon:linux-arm64 .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/rafmon/eventhorizon:linux-arm64
