name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for amd64
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EventHorizon/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ghcr.io/rafmon/eventhorizon:amd64-latest

    - name: Build and push Docker image for arm64
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EventHorizon/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ghcr.io/rafmon/eventhorizon:arm64-latest

    - name: Build and push Docker image for arm/v7
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EventHorizon/Dockerfile
        platforms: linux/arm/v7
        push: true
        tags: ghcr.io/rafmon/eventhorizon:armv7-latest

    - name: Create and push multi-arch manifest
      run: |
        docker manifest create ghcr.io/rafmon/eventhorizon:latest \
          --amend ghcr.io/rafmon/eventhorizon:amd64-latest \
          --amend ghcr.io/rafmon/eventhorizon:arm64-latest \
          --amend ghcr.io/rafmon/eventhorizon:armv7-latest
        docker manifest push ghcr.io/rafmon/eventhorizon:latest